"""initial migration

Revision ID: 0e03c091602d
Revises: 
Create Date: 2025-08-13 12:50:56.342749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e03c091602d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('saccos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('matatu_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saccos'))
    )
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_landmarks_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landmarks'))
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_number', sa.String(), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['locations.id'], name=op.f('fk_routes_destination_id_locations')),
    sa.ForeignKeyConstraint(['origin_id'], ['locations.id'], name=op.f('fk_routes_origin_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_table('sacco_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sacco_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_sacco_routes_route_id_routes')),
    sa.ForeignKeyConstraint(['sacco_id'], ['saccos.id'], name=op.f('fk_sacco_routes_sacco_id_saccos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sacco_routes'))
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sacco_route_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_route_stops_location_id_locations')),
    sa.ForeignKeyConstraint(['sacco_route_id'], ['sacco_routes.id'], name=op.f('fk_route_stops_sacco_route_id_sacco_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops'))
    )
    op.create_table('fares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sacco_route_id', sa.Integer(), nullable=False),
    sa.Column('from_stop_id', sa.Integer(), nullable=False),
    sa.Column('to_stop_id', sa.Integer(), nullable=False),
    sa.Column('fare_amount', sa.Integer(), nullable=False),
    sa.Column('peak_hours', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_stop_id'], ['route_stops.id'], name=op.f('fk_fares_from_stop_id_route_stops')),
    sa.ForeignKeyConstraint(['sacco_route_id'], ['sacco_routes.id'], name=op.f('fk_fares_sacco_route_id_sacco_routes')),
    sa.ForeignKeyConstraint(['to_stop_id'], ['route_stops.id'], name=op.f('fk_fares_to_stop_id_route_stops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fares'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fares')
    op.drop_table('route_stops')
    op.drop_table('sacco_routes')
    op.drop_table('routes')
    op.drop_table('landmarks')
    op.drop_table('saccos')
    op.drop_table('locations')
    # ### end Alembic commands ###
